FROM alpine:3

LABEL author="Muhammad Faiz Rahmadani"
LABEL company="OMNI IT Consulting" website="whitecat20.github.io"

RUN mkdir hello
RUN echo "hello world" > "hello/hello.txt"

CMD cat "hello/hello.txt"