version: '3.9'

services : 
  mongodb-example :
    image : mongo:latest
    container_name: mongodb-example
    ports : 
      - "27017:27017"
    environment :
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin
  
  mongodb-example-express :
    image : mongo-express:latest
    container_name: mongodb-example-express
    ports :
      - "8081:8081"
    environment :
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=admin
    depends_on : 
      - mongodb-example
    